### select-by-conditions
GET http://localhost:8080/emp/select-by-conditions?firstName.eq=Bikash&limit=4
Accept: application/json


### select-page-by-query
GET http://localhost:8080/emp/select-page-by-query?firstName.eq=Bikash&pageSize=10&pageIndex=1
Accept: application/json
